### PR TITLE
Build social sharing CTA

### PR DESCRIPTION
**Pull request by rachelfranklin1**
This PR aims to resolve issue #1 by building the social sharing CTA in a reusable way.  

To test: 
- [x] please test locally and check that the new component looks correct on mobile and iPad 
- [x] please test all social buttons work as expected 

Still to do: 

- [x]  generate the correct [twitter snippet](https://help.twitter.com/en/using-twitter/add-twitter-share-button) and add to twitter button.
- [x] generate a custom Facebook & LinkedIn post from these buttons
- [x] do we want to show the whatsapp button on desktop @shylands ?

Screenshot 2019-05-06 20 18 54

I've added placeholder copy to the pop out window's which are attached to the share buttons. Feel free to suggest/ make changes to this.

### CODE REVIEW

**Comment by rachelfranklin1** [comment]
not sure why the checks are looking for a file ending with `.scss.js` - if anyone can help with these failing checks, it would appreciated 🙏

**Comment by shylands** [comment]
@rachelfranklin1 Awesome work! I think I fixed the checks. I've had a look through it and have a couple of questions that might be answered by a quick overview of how it would work to add this setup for a new page. 

For example, wondering how you get unique text into the share messages for each page and unique URLs. Thanks again!

**Comment by rachelfranklin1** [comment]
Hey @shylands good shout - I hadn't considered making the buttons reusable. That's now fixed. 

I've used props so that we can reuse these buttons on any page and supply whatever message we want to each of them. 

I've also added default props to fall back on if we forget to add a personal message. And last, I added prop-types, mainly to cover the twitter hashtags which need to be supplied as an array, but I added proptypes to the rest of the buttons to be consistent.

Happy to make any further changes, just let me know.

**Comment by shylands** [comment]
Great Rachel understand how it all works now. I think it's pretty much good to go other Whatsapp sharing. I've seen this implementation populates whatsapp for web and mobile apps with a message to share https://saveourfuture.uk/registertovote/

Not sure how it's done, looks to be hooking into the API somehow? If it's too much work let me know and we can always leave it out or see if someone else wants to help. Thanks again!

**Comment by rachelfranklin1** [comment]
No problem @shylands , I've implemented the pop out modal for WhatsApp. 

Feel free to suggest or make copy changes as mine was just for placeholder purposes. Almost there 🤞 🙌

**Comment by shylands** [comment]
@rachelfranklin1 Excellent works perfectly! I'm going to merge this in now. I'll likely tweak the style a bit at and the content but I'll worry about that later. Cheers!

**Pull request merged**
